# Generated by Django 4.2.11 on 2026-04-05 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_book_book_code_book_program_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_record', to='libraryapp.book')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
