# Generated by Django 4.2.11 on 2026-04-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_barcoderecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissue',
            name='employee_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bookissue',
            name='employee_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='student_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='student_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
