# Generated by Django 4.2.11 on 2026-04-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0004_bookissue_employee_id_bookissue_employee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissue',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
